#!/bin/bash

#URL=ws://195.154.218.123:30334
URL=wss://kusama-rpc.polkadot.io
ADDRESS=/ip4/195.154.218.123/tcp/30333
#/p2p/12D3KooWFiabPjp5Y5gADpEYzVtkNUKeSAUJB2QtPFMXsi6qwi1y
# ADDRESS=/dns/kusama-bootnode-0.polkadot.io/tcp/30333

#URL=wss://paseo-asset-hub-next-rpc.polkadot.io
#ADDRESS=/dns4/paseo-asset-hub-next-collator-node-0.parity-testnet.parity.io/tcp/443/wss

#METHOD="account_nonce"
METHOD="account_nonce,ParachainHost_candidate_events,ParachainHost_disputes,ParachainHost_validators,BabeApi_current_epoch,GrandpaApi_grandpa_authorities,Metadata_metadata"

DURATION=${DURATION:-120}
# counts per connection
COUNT=${COUNT:-1000}
CONCURRENCY=${CONCURRENCY:-20}
CONNECTIONS=${CONNECTIONS:-1}

export RUST_LOG=info

# Build once: cargo build --release -p subp2p-explorer-cli
./target/release/subp2p-explorer-cli spam-light   --url $URL   --address $ADDRESS  --method $METHOD   --count $COUNT --concurrency $CONCURRENCY --connections $CONNECTIONS --timeout $DURATION

