#!/bin/bash

#URL=ws://195.154.218.123:30334
URL=wss://kusama-rpc.polkadot.io
ADDRESS=/ip4/195.154.218.123/tcp/30333
#/p2p/12D3KooWFiabPjp5Y5gADpEYzVtkNUKeSAUJB2QtPFMXsi6qwi1y

#URL=wss://paseo-asset-hub-next-rpc.polkadot.io
#ADDRESS=/dns4/paseo-asset-hub-next-collator-node-0.parity-testnet.parity.io/tcp/443/wss

#METHOD_DFLT="account_nonce"
#METHOD_DFLT="account_nonce,ParachainHost_candidate_events,ParachainHost_disputes,ParachainHost_validators,BabeApi_current_epoch,GrandpaApi_grandpa_authorities,Metadata_metadata"

#METHOD_DFLT="warp_code"
# warp sync calls
#METHOD_DFLT="babe_configuration,babe_current_epoch,babe_next_epoch,aura_slot_duration,aura_authorities"
METHOD_DFLT="babe_configuration,babe_current_epoch,babe_next_epoch"


METHOD=${METHOD:-$METHOD_DFLT}
DURATION=${DURATION:-120}
RATE=${RATE:-6000}
CLIENTS=${CLIENTS:-1000}

export RUST_LOG=info

# Build once: cargo build --release -p subp2p-explorer-cli
./target/release/subp2p-explorer-cli soak-light   --url $URL   --address $ADDRESS  --method $METHOD   --rate $RATE --duration $DURATION --clients $CLIENTS

